### ISSUE TITLE
有一个小bug

### ISSUE THREAD

**Issue by Tomsawyerhu** [cdfmlr/murecom-verse-1#3]
在请求歌曲评论和歌词的时候，用到两个管道，并用两次for+select去分别读取。由于发送方调用了close关闭管道，导致有可能同一个管道被读到两次(真实值+零值)。这个在我跑数据的时候每次结果不一致发现的
解决方式：不用关闭管道，让go自行清理

**Comment by Tomsawyerhu** [comment]
<img width="808" alt="image" src="https://github.com/cdfmlr/murecom-verse-1/assets/46986832/5cdc7d49-f51a-469c-8c2f-fd829fb7e3b7">
line 150

**Comment by cdfmlr** [comment]
这里如果不 close 的话会好像是会阻碍 gc 导致 goroutine 泄漏
