### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Kaia56** [cdfmlr/murecom-verse-1#4]
大佬您好，请问db里面url是哪个链接呀，谢谢您

**Comment by cdfmlr** [comment]
哪个db?

**Comment by Kaia56** [comment]
db里面应该url，请问是哪个链接😭



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 3, 2024 20:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cdfmlr/murecom-verse-1] help (Issue #4)




 
哪个db?

**Comment by cdfmlr** [comment]
你问的是哪个文件的里的db？😭

**Comment by Kaia56** [comment]
就是运行它issue里面那个config里面那个，然后代码提示db是空的🥺



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 3, 2024 20:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cdfmlr/murecom-verse-1] help (Issue #4)




 
你问的是哪个文件的里的db？😭

**Comment by cdfmlr** [comment]
`recommend-text.ipynb` 里的 config 嘛？

```py
with open('config.json') as f:
    config = json.load(f)
```

焯不记得怎么配了😭本地的目录也被我删了。。

我试试还能不能从 time machine 里拉出来哈。

**Comment by cdfmlr** [comment]
居然还真找到了。。

我添加了一些示例的配置文件，需要根据你的实际情况进行修改: https://github.com/cdfmlr/murecom-verse-1/commit/74737de0d184a9da83e309bbc19d5170da9b445d

**Comment by Kaia56** [comment]
天哪，真的是太感谢了！哈哈哈哈哈哈🥰🥰🥰



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 3, 2024 21:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cdfmlr/murecom-verse-1] help (Issue #4)




 
居然还真找到了。。
 
我添加了一些示例的配置文件，需要根据你的实际情况进行修改: 74737de

**Comment by cdfmlr** [comment]
solved by 74737de0d184a9da83e309bbc19d5170da9b445d
