### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by Superhu003** [cdfmlr/murecom-verse-1#8]
大佬，我现在只是想实现给定一首歌对其进行情感分析。可以实现界面功能上传歌曲并且进行展示，请问您有什么建议吗？
我的项目名称是音乐情感分析系统设计与实现。

**Comment by cdfmlr** [comment]
可以看看我们的另一个项目: https://github.com/murchinroom/emomusic 在这个里面，我们借助卷积神经网络，分析输入的 mp3 音频，得到一个 valence-arouse 模型表示的情感值。

**Comment by Superhu003** [comment]
大佬，我有一些困难急需帮助，请问可以添加一下您的微信请教一下您吗（哭）

**Comment by cdfmlr** [comment]
可以，你直接搜，和 github 同名。

**Comment by Superhu003** [comment]
我添加你了大佬
